name: update-every-15m-Fri-Sun
on:
  schedule:
    - cron: '*/15 * * * 5,6,0'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call F1 API route fetching new documents
        run: |
          curl --request GET \
          --url '${{ secrets.UPDATE_F1_ENDPOINT }}' \
          --header 'Authorization: Bearer ${{ secrets.CRON_JOB_SECRET }}'
      - name: Call F2 API route fetching new documents
        run: |
          curl --request GET \
          --url '${{ secrets.UPDATE_F2_ENDPOINT }}' \
          --header 'Authorization: Bearer ${{ secrets.CRON_JOB_SECRET }}'
      - name: Call F3 API route fetching new documents
        run: |
          curl --request GET \
          --url '${{ secrets.UPDATE_F3_ENDPOINT }}' \
          --header 'Authorization: Bearer ${{ secrets.CRON_JOB_SECRET }}'
